package net.sigmabeta.chipbox.strings

import net.sigmabeta.sage.ui.SageStringId

enum class ChipboxStringId : SageStringId {
    ACCY_OCL_CHECKBOX,
    ACCY_OCL_DROPDOWN,
    ACCY_OCL_RATING,
    ACCY_OCL_SINGLE_LINE,
    ACCY_OCL_VALUE,
    ACCY_ST_DESC_CHECKED,
    ACCY_ST_DESC_LOADING,
    ACCY_ST_DESC_UNCHECKED,
    APPUI_TAB_LIBRARY,
    APPUI_TAB_SEARCH,
    APPUI_TAB_SETTINGS,
    LIBRARY_BROWSE_BY_GAME,
    LIBRARY_BROWSE_BY_ARTIST,
    LIBRARY_BROWSE_ALL_TRACKS,
    GAME_DETAIL_SECTION_SONGS,
    GAME_DETAIL_SECTION_ARTISTS,
    GAME_DETAIL_CTA_PLAY_ALL,
    GAME_DETAIL_CTA_SHUFFLE_ALL,
}
