/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sigmabeta_chipbox_util_external_FileNativeKt */

#ifndef _Included_net_sigmabeta_chipbox_util_external_FileNativeKt
#define _Included_net_sigmabeta_chipbox_util_external_FileNativeKt
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getPlatformNativeGme
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getPlatformNativeGme
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoSetupNativeGme
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoSetupNativeGme
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoGetTrackCountGme
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoGetTrackCountGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoSetTrackNumberNativeGme
 * Signature: (I)V
 */
JNIEXPORT void JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoSetTrackNumberNativeGme
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoTeardownNativeGme
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoTeardownNativeGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileTrackLengthGme
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileTrackLengthGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileIntroLengthGme
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileIntroLengthGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileLoopLengthGme
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileLoopLengthGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileTitleGme
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileTitleGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileGameTitleGme
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileGameTitleGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFilePlatformGme
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL
Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFilePlatformGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileArtistGme
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileArtistGme
  (JNIEnv *, jclass);

jbyteArray get_java_byte_array(JNIEnv *, const char *);

void teardown();

#ifdef __cplusplus
}
#endif
#endif

