/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sigmabeta_chipbox_util_external_FileNativeKt */

#ifndef _Included_net_sigmabeta_chipbox_util_external_FileNativeKt
#define _Included_net_sigmabeta_chipbox_util_external_FileNativeKt
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getPlatformNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getPlatformNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoSetupNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoSetupNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoGetTrackCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoGetTrackCount
  (JNIEnv *, jclass);
  
/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoSetTrackNumberNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoSetTrackNumberNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    fileInfoTeardownNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_fileInfoTeardownNative
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileTrackLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileTrackLength
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileIntroLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileIntroLength
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileLoopLength
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileLoopLength
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileTitle
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileTitle
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileGameTitle
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileGameTitle
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFilePlatform
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFilePlatform
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_FileNativeKt
 * Method:    getFileArtist
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sigmabeta_chipbox_util_external_FileNativeKt_getFileArtist
  (JNIEnv *, jclass);

jbyteArray get_java_byte_array(JNIEnv *, const char *);

void teardown();

#ifdef __cplusplus
}
#endif
#endif

