/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sigmabeta_chipbox_util_external_PlayerNativeKt */

#ifndef _Included_net_sigmabeta_chipbox_util_external_PlayerNativeKt
#define _Included_net_sigmabeta_chipbox_util_external_PlayerNativeKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    loadFileGme
 * Signature: (Ljava/lang/String;IIJ)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_loadFileGme
  (JNIEnv *, jclass, jstring, jint, jint, jlong, jint);

JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_loadFileVgm
        (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    readNextSamplesGme
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_readNextSamplesGme
  (JNIEnv *, jclass, jshortArray);

JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_readNextSamplesVgm
        (JNIEnv *, jclass, jshortArray);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    getMillisPlayedGme
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_getMillisPlayedGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    seekNativeGme
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_seekNativeGme
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    setTempoNativeGme
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_setTempoNativeGme
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    getVoiceCountNativeGme
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_getVoiceCountNativeGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    getVoiceNameNativeGme
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_getVoiceNameNativeGme
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    muteVoiceNativeGme
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_muteVoiceNativeGme
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    isTrackOverGme
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_isTrackOverGme
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    teardownGme
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_teardownGme
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_teardownVgm
  (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeKt
 * Method:    getLastErrorGme
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeKt_getLastErrorGme
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
