@file:Suppress("MagicNumber")

package net.sigmabeta.chipbox.ui.theme.api

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF735C0C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE08B)
val onPrimaryContainerLight = Color(0xFF584400)
val secondaryLight = Color(0xFF625690)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE7DEFF)
val onSecondaryContainerLight = Color(0xFF4A3E76)
val tertiaryLight = Color(0xFF435E91)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD7E2FF)
val onTertiaryContainerLight = Color(0xFF2A4678)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F1)
val onBackgroundLight = Color(0xFF1F1B13)
val surfaceLight = Color(0xFFFFF8F1)
val onSurfaceLight = Color(0xFF1F1B13)
val surfaceVariantLight = Color(0xFFEBE1CF)
val onSurfaceVariantLight = Color(0xFF4C4639)
val outlineLight = Color(0xFF7E7667)
val outlineVariantLight = Color(0xFFCFC6B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF343027)
val inverseOnSurfaceLight = Color(0xFFF8F0E2)
val inversePrimaryLight = Color(0xFFE3C46D)
val surfaceDimLight = Color(0xFFE1D9CC)
val surfaceBrightLight = Color(0xFFFFF8F1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF3E5)
val surfaceContainerLight = Color(0xFFF5EDDF)
val surfaceContainerHighLight = Color(0xFFF0E7D9)
val surfaceContainerHighestLight = Color(0xFFEAE1D4)

val primaryLightMediumContrast = Color(0xFF443400)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF836A1C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF392D64)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF71659F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF163566)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF526DA1)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F1)
val onBackgroundLightMediumContrast = Color(0xFF1F1B13)
val surfaceLightMediumContrast = Color(0xFFFFF8F1)
val onSurfaceLightMediumContrast = Color(0xFF141109)
val surfaceVariantLightMediumContrast = Color(0xFFEBE1CF)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B3629)
val outlineLightMediumContrast = Color(0xFF585244)
val outlineVariantLightMediumContrast = Color(0xFF736C5D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF343027)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF8F0E2)
val inversePrimaryLightMediumContrast = Color(0xFFE3C46D)
val surfaceDimLightMediumContrast = Color(0xFFCDC6B9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F1)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFBF3E5)
val surfaceContainerLightMediumContrast = Color(0xFFF0E7D9)
val surfaceContainerHighLightMediumContrast = Color(0xFFE4DCCE)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD9D1C3)

val primaryLightHighContrast = Color(0xFF382B00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF5A4700)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2F2359)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4D4179)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF082B5B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2D497A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F1)
val onBackgroundLightHighContrast = Color(0xFF1F1B13)
val surfaceLightHighContrast = Color(0xFFFFF8F1)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEBE1CF)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF312C20)
val outlineVariantLightHighContrast = Color(0xFF4E493B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF343027)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE3C46D)
val surfaceDimLightHighContrast = Color(0xFFBFB8AB)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F1)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF8F0E2)
val surfaceContainerLightHighContrast = Color(0xFFEAE1D4)
val surfaceContainerHighLightHighContrast = Color(0xFFDBD3C6)
val surfaceContainerHighestLightHighContrast = Color(0xFFCDC6B9)

val primaryDark = Color(0xFFE3C46D)
val onPrimaryDark = Color(0xFF3D2F00)
val primaryContainerDark = Color(0xFF584400)
val onPrimaryContainerDark = Color(0xFFFFE08B)
val secondaryDark = Color(0xFFCCBDFF)
val onSecondaryDark = Color(0xFF33275E)
val secondaryContainerDark = Color(0xFF4A3E76)
val onSecondaryContainerDark = Color(0xFFE7DEFF)
val tertiaryDark = Color(0xFFACC7FF)
val onTertiaryDark = Color(0xFF0F2F60)
val tertiaryContainerDark = Color(0xFF2A4678)
val onTertiaryContainerDark = Color(0xFFD7E2FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF16130B)
val onBackgroundDark = Color(0xFFEAE1D4)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFEAE1D4)
val surfaceVariantDark = Color(0xFF4C4639)
val onSurfaceVariantDark = Color(0xFFCFC6B4)
val outlineDark = Color(0xFF989080)
val outlineVariantDark = Color(0xFF4C4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE1D4)
val inverseOnSurfaceDark = Color(0xFF343027)
val inversePrimaryDark = Color(0xFF735C0C)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3D392F)
val surfaceContainerLowestDark = Color(0xFF110E07)
val surfaceContainerLowDark = Color(0xFF1F1B13)
val surfaceContainerDark = Color(0xFF231F17)
val surfaceContainerHighDark = Color(0xFF2D2A21)
val surfaceContainerHighestDark = Color(0xFF38342B)

val primaryDarkMediumContrast = Color(0xFFFAD980)
val onPrimaryDarkMediumContrast = Color(0xFF302400)
val primaryContainerDarkMediumContrast = Color(0xFFA98E3D)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE1D7FF)
val onSecondaryDarkMediumContrast = Color(0xFF281C53)
val secondaryContainerDarkMediumContrast = Color(0xFF9588C6)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFCEDCFF)
val onTertiaryDarkMediumContrast = Color(0xFF002453)
val tertiaryContainerDarkMediumContrast = Color(0xFF7691C7)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF16130B)
val onBackgroundDarkMediumContrast = Color(0xFFEAE1D4)
val surfaceDarkMediumContrast = Color(0xFF16130B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4C4639)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE5DBC9)
val outlineDarkMediumContrast = Color(0xFFBAB1A0)
val outlineVariantDarkMediumContrast = Color(0xFF97907F)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEAE1D4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF594600)
val surfaceDimDarkMediumContrast = Color(0xFF16130B)
val surfaceBrightDarkMediumContrast = Color(0xFF49443A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
val surfaceContainerLowDarkMediumContrast = Color(0xFF211D15)
val surfaceContainerDarkMediumContrast = Color(0xFF2B271F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF363229)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF423D34)

val primaryDarkHighContrast = Color(0xFFFFEFC9)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFDFC069)
val onPrimaryContainerDarkHighContrast = Color(0xFF100A00)
val secondaryDarkHighContrast = Color(0xFFF4EDFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC8BAFB)
val onSecondaryContainerDarkHighContrast = Color(0xFF0D0035)
val tertiaryDarkHighContrast = Color(0xFFECEFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA8C3FC)
val onTertiaryContainerDarkHighContrast = Color(0xFF000A21)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF16130B)
val onBackgroundDarkHighContrast = Color(0xFFEAE1D4)
val surfaceDarkHighContrast = Color(0xFF16130B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4C4639)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF9EFDC)
val outlineVariantDarkHighContrast = Color(0xFFCBC2B0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEAE1D4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF594600)
val surfaceDimDarkHighContrast = Color(0xFF16130B)
val surfaceBrightDarkHighContrast = Color(0xFF545045)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF231F17)
val surfaceContainerDarkHighContrast = Color(0xFF343027)
val surfaceContainerHighDarkHighContrast = Color(0xFF3F3B31)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4B463C)

val ChipboxLight = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val ChipboxDark = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
