@file:Suppress("MagicNumber")

package net.sigmabeta.chipbox.ui.theme.api

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8C4A60)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD9E2)
val onPrimaryContainerLight = Color(0xFF703348)
val secondaryLight = Color(0xFF74565F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E2)
val onSecondaryContainerLight = Color(0xFF5A3F47)
val tertiaryLight = Color(0xFF7C5635)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDCC1)
val onTertiaryContainerLight = Color(0xFF623F20)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF22191C)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF22191C)
val surfaceVariantLight = Color(0xFFF2DDE1)
val onSurfaceVariantLight = Color(0xFF514347)
val outlineLight = Color(0xFF837377)
val outlineVariantLight = Color(0xFFD5C2C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372E30)
val inverseOnSurfaceLight = Color(0xFFFDEDEF)
val inversePrimaryLight = Color(0xFFFFB1C8)
val surfaceDimLight = Color(0xFFE6D6D9)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F2)
val surfaceContainerLight = Color(0xFFFAEAED)
val surfaceContainerHighLight = Color(0xFFF5E4E7)
val surfaceContainerHighestLight = Color(0xFFEFDFE1)

val primaryLightMediumContrast = Color(0xFF5B2238)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF9D586F)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF482F37)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF84656D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF4E2F11)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF8D6542)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F8)
val onBackgroundLightMediumContrast = Color(0xFF22191C)
val surfaceLightMediumContrast = Color(0xFFFFF8F8)
val onSurfaceLightMediumContrast = Color(0xFF170F11)
val surfaceVariantLightMediumContrast = Color(0xFFF2DDE1)
val onSurfaceVariantLightMediumContrast = Color(0xFF403336)
val outlineLightMediumContrast = Color(0xFF5D4F52)
val outlineVariantLightMediumContrast = Color(0xFF79696D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF372E30)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFDEDEF)
val inversePrimaryLightMediumContrast = Color(0xFFFFB1C8)
val surfaceDimLightMediumContrast = Color(0xFFD2C3C5)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F8)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF0F2)
val surfaceContainerLightMediumContrast = Color(0xFFF5E4E7)
val surfaceContainerHighLightMediumContrast = Color(0xFFE9D9DC)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDDCED0)

val primaryLightHighContrast = Color(0xFF4F182E)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF72354B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3D252D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5D424A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF432508)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF644122)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F8)
val onBackgroundLightHighContrast = Color(0xFF22191C)
val surfaceLightHighContrast = Color(0xFFFFF8F8)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF2DDE1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF35292C)
val outlineVariantLightHighContrast = Color(0xFF544649)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF372E30)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFB1C8)
val surfaceDimLightHighContrast = Color(0xFFC4B5B8)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F8)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFDEDEF)
val surfaceContainerLightHighContrast = Color(0xFFEFDFE1)
val surfaceContainerHighLightHighContrast = Color(0xFFE0D1D3)
val surfaceContainerHighestLightHighContrast = Color(0xFFD2C3C5)

val primaryDark = Color(0xFFFFB1C8)
val onPrimaryDark = Color(0xFF541D32)
val primaryContainerDark = Color(0xFF703348)
val onPrimaryContainerDark = Color(0xFFFFD9E2)
val secondaryDark = Color(0xFFE3BDC6)
val onSecondaryDark = Color(0xFF422931)
val secondaryContainerDark = Color(0xFF5A3F47)
val onSecondaryContainerDark = Color(0xFFFFD9E2)
val tertiaryDark = Color(0xFFEFBD94)
val onTertiaryDark = Color(0xFF48290B)
val tertiaryContainerDark = Color(0xFF623F20)
val onTertiaryContainerDark = Color(0xFFFFDCC1)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191113)
val onBackgroundDark = Color(0xFFEFDFE1)
val surfaceDark = Color(0xFF191113)
val onSurfaceDark = Color(0xFFEFDFE1)
val surfaceVariantDark = Color(0xFF514347)
val onSurfaceVariantDark = Color(0xFFD5C2C6)
val outlineDark = Color(0xFF9E8C90)
val outlineVariantDark = Color(0xFF514347)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEFDFE1)
val inverseOnSurfaceDark = Color(0xFF372E30)
val inversePrimaryDark = Color(0xFF8C4A60)
val surfaceDimDark = Color(0xFF191113)
val surfaceBrightDark = Color(0xFF413739)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF22191C)
val surfaceContainerDark = Color(0xFF261D20)
val surfaceContainerHighDark = Color(0xFF31282A)
val surfaceContainerHighestDark = Color(0xFF3C3235)

val primaryDarkMediumContrast = Color(0xFFFFD0DC)
val onPrimaryDarkMediumContrast = Color(0xFF471227)
val primaryContainerDarkMediumContrast = Color(0xFFC67B92)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFAD2DC)
val onSecondaryDarkMediumContrast = Color(0xFF361F26)
val secondaryContainerDarkMediumContrast = Color(0xFFAA8891)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD4B3)
val onTertiaryDarkMediumContrast = Color(0xFF3B1F03)
val tertiaryContainerDarkMediumContrast = Color(0xFFB48862)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF191113)
val onBackgroundDarkMediumContrast = Color(0xFFEFDFE1)
val surfaceDarkMediumContrast = Color(0xFF191113)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF514347)
val onSurfaceVariantDarkMediumContrast = Color(0xFFECD7DB)
val outlineDarkMediumContrast = Color(0xFFC0ADB1)
val outlineVariantDarkMediumContrast = Color(0xFF9D8C90)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF31282A)
val inversePrimaryDarkMediumContrast = Color(0xFF71344A)
val surfaceDimDarkMediumContrast = Color(0xFF191113)
val surfaceBrightDarkMediumContrast = Color(0xFF4C4244)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0607)
val surfaceContainerLowDarkMediumContrast = Color(0xFF241B1E)
val surfaceContainerDarkMediumContrast = Color(0xFF2F2628)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3A3032)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF453B3D)

val primaryDarkHighContrast = Color(0xFFFFEBEF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFEABC4)
val onPrimaryContainerDarkHighContrast = Color(0xFF20000C)
val secondaryDarkHighContrast = Color(0xFFFFEBEF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFDEB9C2)
val onSecondaryContainerDarkHighContrast = Color(0xFF18060C)
val tertiaryDarkHighContrast = Color(0xFFFFEDE0)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFEBB990)
val onTertiaryContainerDarkHighContrast = Color(0xFF160800)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF191113)
val onBackgroundDarkHighContrast = Color(0xFFEFDFE1)
val surfaceDarkHighContrast = Color(0xFF191113)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF514347)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFFEBEF)
val outlineVariantDarkHighContrast = Color(0xFFD1BEC2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEFDFE1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF71344A)
val surfaceDimDarkHighContrast = Color(0xFF191113)
val surfaceBrightDarkHighContrast = Color(0xFF584D50)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF261D20)
val surfaceContainerDarkHighContrast = Color(0xFF372E30)
val surfaceContainerHighDarkHighContrast = Color(0xFF43393B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4F4446)

val ChipboxLight = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val ChipboxDark = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
