/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sigmabeta_chipbox_backend_psf_BackendImpl */

#ifndef _Included_net_sigmabeta_chipbox_backend_psf_BackendImpl
#define _Included_net_sigmabeta_chipbox_backend_psf_BackendImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    loadFile
 * Signature: (Ljava/lang/String;IIJJ)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_loadFile
        (JNIEnv *, jobject, jstring, jint, jint, jlong, jlong);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    readNextSamples
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_readNextSamples
        (JNIEnv *, jobject, jshortArray);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    getMillisPlayed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_getMillisPlayed
        (JNIEnv *, jobject);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    seek
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_seek
        (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    setTempo
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_setTempo
        (JNIEnv *, jobject, jdouble);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    getVoiceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_getVoiceCount
        (JNIEnv *, jobject);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    getVoiceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_getVoiceName
        (JNIEnv *, jobject, jint);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    muteVoice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_muteVoice
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    isTrackOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_isTrackOver
        (JNIEnv *, jobject);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_teardown
        (JNIEnv *, jobject);

/*
 * Class:     net_sigmabeta_chipbox_backend_psf_BackendImpl
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_backend_psf_BackendImpl_getLastError
        (JNIEnv *, jobject);

void loadFileInternal(const char * filename_c_str, jint rate, jlong buffer_size, jlong fade_time_ms);

uint64_t getMillisPlayedInternal();

uint64_t convert_samples_to_ms(int sample_rate, uint64_t samples);
uint64_t convert_ms_to_samples(int sample_rate, uint64_t ms);

const char * read_whole_file(const char * path, int64_t * size);

void processFadeOut(short * buffer_to_fade,
                    uint64_t buffer_length_samples,
                    uint64_t first_sample_index,
                    uint64_t fade_start_threshold_samples,
                    uint64_t fade_time_samples);

void teardownInternal();

#ifdef __cplusplus
}
#endif
#endif
