/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt */

#ifndef _Included_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
#define _Included_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
 * Method:    loadFileVgm
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt_loadFileVgm
        (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
 * Method:    readNextSamplesVgm
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt_readNextSamplesVgm
        (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
 * Method:    teardownVgm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt_teardownVgm
        (JNIEnv *, jclass);

/*
 * Class:     net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt
 * Method:    getLastErrorVgm
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sigmabeta_chipbox_util_external_PlayerNativeVgmKt_getLastErrorVgm
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
