#!/usr/bin/env bash
# Generate docs/download.md for a published release. Called by release.yml's publish job so the
# download page's links track each release automatically — no hand-editing per version.
#
#   scripts/gen-download-page.sh <tag> <assets-dir>   # prints the page to stdout
#
# <assets-dir> holds the actual published asset files; links are built from their real names, so the
# APKs' app-versioning "<tag>.<commits>" suffix is picked up without reconstructing it, and a
# platform with no asset this release (e.g. macOS) is simply omitted.
set -euo pipefail

TAG="${1:?usage: gen-download-page.sh <tag> <assets-dir>}"
DIR="${2:?usage: gen-download-page.sh <tag> <assets-dir>}"
BASE="https://github.com/sigmabeta/chipbox/releases/download/$TAG"

# First asset filename matching a regex (empty if none). `|| true` so a no-match (e.g. no .dmg
# this release) doesn't trip `set -e`/`pipefail`.
pick() { find "$DIR" -maxdepth 1 -type f -printf '%f\n' 2>/dev/null | grep -E "$1" | sort | head -1 || true; }

apk_universal=$(pick 'universal\.apk$')
apk_arm64=$(pick 'arm64-v8a\.apk$')
apk_x86=$(pick 'x86_64\.apk$')
deb=$(pick '\.deb$')
rpm=$(pick '\.rpm$')
msi=$(pick '\.msi$')
dmg=$(pick '\.dmg$')

# button <label> <filename> [extra-classes]
button() { printf '[%s](%s/%s){ .md-button%s }\n' "$1" "$BASE" "$2" "${3:-}"; }

cat <<EOF
<!-- Generated by scripts/gen-download-page.sh on each release. Do not edit by hand. -->
# Download

Current release: **[$TAG](https://github.com/sigmabeta/chipbox/releases/tag/$TAG)**.
See the changelog and every asset on the
[releases page](https://github.com/sigmabeta/chipbox/releases).

## Android

Android 8.0 (API 26) or newer. The universal APK runs on any device; the
per-architecture builds are smaller.

EOF

[ -n "$apk_universal" ] && button ":material-android: Download APK (universal) :material-download:" "$apk_universal" " .md-button--primary"
echo "[Build it yourself](build.md){ .md-button }"

if [ -n "$apk_arm64" ] || [ -n "$apk_x86" ]; then
  echo
  line="Smaller per-architecture builds:"
  [ -n "$apk_arm64" ] && line="$line [arm64-v8a]($BASE/$apk_arm64)"
  [ -n "$apk_arm64" ] && [ -n "$apk_x86" ] && line="$line ·"
  [ -n "$apk_x86" ] && line="$line [x86_64]($BASE/$apk_x86)"
  echo "$line."
fi

printf '\n## Desktop\n\nSelf-contained installers with a bundled Java runtime — nothing else to install.\n'
[ -z "$dmg" ] && printf 'macOS isn'\''t supported yet.\n'

if [ -n "$msi" ]; then
  printf '\n### Windows\n\n'
  button ":material-microsoft-windows: Download .msi :material-download:" "$msi" " .md-button--primary"
fi

if [ -n "$deb" ] || [ -n "$rpm" ]; then
  printf '\n### Linux\n\n'
  [ -n "$deb" ] && button ":material-debian: .deb — Debian / Ubuntu :material-download:" "$deb" " .md-button--primary"
  [ -n "$rpm" ] && button ":material-redhat: .rpm — Fedora / RHEL :material-download:" "$rpm"
fi

if [ -n "$dmg" ]; then
  printf '\n### macOS\n\n'
  button ":material-apple: Download .dmg :material-download:" "$dmg" " .md-button--primary"
fi

printf '\nPrefer to build from source? See **[Build from source](build.md)**.\n'
