#!/usr/bin/env python3
"""
One-off helper: parse every cbox/android/strings/api/src/main/res/values/strings-*.xml
file and emit the JVM string map for the headless desktop target. The map is keyed
by the `ChipboxStringId` enum entries (in the same `net.sigmabeta.chipbox.strings`
package) — the Android side uses `R.string.<lowercase_id>`, the JVM side just keeps
the English text inline.

Re-run whenever strings are added to the XMLs. The Kotlin code references each
`ChipboxStringId.X` symbol, so missing entries surface as compile errors instead of
runtime "no mapping" failures.
"""
from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
XML_DIR = REPO / "cbox/android/strings/api/src/main/res/values"
ENUM_FILE = REPO / "cbox/common/strings/api/src/commonMain/kotlin/net/sigmabeta/chipbox/strings/ChipboxStringId.kt"
ENUM_FILE_FALLBACK = REPO / "cbox/common/strings/api/src/main/java/net/sigmabeta/chipbox/strings/ChipboxStringId.kt"
OUT = REPO / "apps/jvm/src/main/java/net/sigmabeta/chipbox/jvm/strings/JvmChipboxStrings.kt"


def kotlin_escape(s: str) -> str:
    # Android string XML uses Java/Android escapes: \\n, \\', \\". Translate the
    # XML-decoded text into a Kotlin double-quoted string literal.
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return "".join(out)


def unescape_xml_string(raw: str) -> str:
    # Android strings.xml escapes literal apostrophes / quotes with backslashes;
    # ElementTree returns the raw inner text (still escaped). Decode the small
    # subset that actually appears in chipbox strings.
    return raw.replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n")


def collect_enum_ids() -> set[str]:
    path = ENUM_FILE if ENUM_FILE.exists() else ENUM_FILE_FALLBACK
    if not path.exists():
        print(f"could not locate ChipboxStringId.kt under {path.parent}", file=sys.stderr)
        return set()
    ids: set[str] = set()
    for line in path.read_text().splitlines():
        stripped = line.strip().rstrip(",")
        if re.fullmatch(r"[A-Z_][A-Z0-9_]*", stripped):
            ids.add(stripped)
    return ids


def collect() -> list[tuple[str, str]]:
    enum_ids = collect_enum_ids()
    entries: list[tuple[str, str]] = []
    skipped: list[str] = []
    xmls = sorted(list(XML_DIR.glob("strings-*.xml")) + list(XML_DIR.glob("strings.xml")))
    for xml in xmls:
        root = ET.parse(xml).getroot()
        for el in root.findall("string"):
            name = el.get("name")
            if name is None:
                continue
            upper = name.upper()
            if enum_ids and upper not in enum_ids:
                skipped.append(upper)
                continue
            text = "".join(el.itertext())
            entries.append((upper, unescape_xml_string(text)))
    entries.sort()
    if skipped:
        print(
            f"skipped {len(skipped)} XML string(s) with no matching ChipboxStringId entry: "
            f"{', '.join(sorted(set(skipped)))}",
            file=sys.stderr,
        )
    missing = enum_ids - {name for name, _ in entries}
    if missing:
        print(
            f"WARN: {len(missing)} ChipboxStringId entries have no matching strings.xml entry: "
            f"{', '.join(sorted(missing))}",
            file=sys.stderr,
        )
    return entries


def main() -> int:
    entries = collect()
    if not entries:
        print(f"no strings found under {XML_DIR}", file=sys.stderr)
        return 1
    lines = [
        '@file:Suppress("MaxLineLength")',
        "",
        "package net.sigmabeta.chipbox.jvm.strings",
        "",
        "import net.sigmabeta.chipbox.strings.ChipboxStringId",
        "import net.sigmabeta.sage.ui.SageStringId",
        "",
        "// Auto-generated by scripts/gen_jvm_strings.py — do not edit by hand.",
        "// Source of truth: cbox/android/strings/api/src/main/res/values/strings-*.xml.",
        "// Re-run the script after editing those XMLs to keep the JVM target in sync.",
        "val chipboxJvmStrings: Map<SageStringId, String> = mapOf(",
    ]
    for name, text in entries:
        lines.append(f'    ChipboxStringId.{name} to "{kotlin_escape(text)}",')
    lines.append(")")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(entries)} strings)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
