plugins {
    alias(libs.plugins.sage.jvm)
    alias(libs.plugins.ksp)
    application
}

application {
    mainClass.set("net.sigmabeta.chipbox.jvm.MainKt")
}

// libgme.so is host-built (see apps/jvm/README) into apps/jvm/libs and loaded at runtime via
// System.loadLibrary("gme"); point the JVM library path at it for `gradle run`.
val nativeLibsDir = layout.projectDirectory.dir("libs")

tasks.named<JavaExec>("run") {
    systemProperty("java.library.path", nativeLibsDir.asFile.absolutePath)
}

// Emit a ready-to-run `java` invocation (no Gradle at runtime). Many modules share a jar
// basename (real.jar/api.jar), which breaks the flat-lib `installDist`; an explicit
// classpath of full, unique jar paths sidesteps that. Writes build/run-standalone.sh.
tasks.register("standaloneScript") {
    val rtFiles: FileCollection = configurations.getByName("runtimeClasspath")
    val jarFile = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val mainClass = application.mainClass
    val libDir = nativeLibsDir.asFile.absolutePath
    val outFile = layout.buildDirectory.file("run-standalone.sh")
    inputs.files(rtFiles, jarFile)
    outputs.file(outFile)
    doLast {
        val cp = (listOf(jarFile.get().asFile) + rtFiles.files)
            .joinToString(":") { it.absolutePath }
        val f = outFile.get().asFile
        f.writeText(
            "#!/usr/bin/env bash\n" +
                "# Generated by :apps:jvm:standaloneScript — runs without Gradle.\n" +
                "exec java -Djava.library.path='$libDir' \\\n" +
                "  -cp '$cp' \\\n" +
                "  ${mainClass.get()} \"\$@\"\n"
        )
        f.setExecutable(true)
        logger.lifecycle("Wrote ${f.absolutePath}")
    }
}

dependencies {
    implementation(projects.cbox.android.player.generator.real)
    implementation(projects.cbox.android.player.emulators.gba.real)
    implementation(projects.cbox.android.player.emulators.gme.real)
    implementation(projects.cbox.android.player.emulators.psf.real)
    implementation(projects.cbox.android.player.emulators.ssf.real)
    implementation(projects.cbox.android.player.emulators.twosf.real)
    implementation(projects.cbox.android.player.emulators.usf.real)
    implementation(projects.cbox.android.player.emulators.vgm.real)
    implementation(projects.cbox.common.contentsource.api)
    implementation(projects.cbox.common.player.speaker.fake)
    implementation(projects.cbox.common.player.buffer.real)
    implementation(projects.cbox.common.player.common.api)
    implementation(projects.cbox.common.repository.api)
    implementation(projects.cbox.common.models.api)

    // Room KMP database used as the JVM target's real library (replaces the
    // SingleTrackRepository shim for `scan` / `play` modes). `sqlite-bundled`
    // is the cross-platform Room driver Android doesn't need.
    implementation(projects.cbox.android.repository.real)
    implementation(projects.cbox.android.database.all)
    implementation(libs.sqlite.bundled)

    // Shared scanner — uses the new LibrarySource interface; LocalFileContentSource
    // is the JVM impl, the Android twin is AndroidFileContentSource (SAF).
    implementation(projects.cbox.android.scanner.real)
    implementation(projects.cbox.common.readers.api)

    // Plain Dagger — the headless JVM target assembles its own @Component. Hilt is
    // Android-only by design, so the JVM-side `@Module` classes (see jvm/di/) duplicate
    // the trivial @Provides for each emulator + buffer + repository binding; that's
    // simpler than wiring sage.android Hilt modules into a sage.jvm app's classpath.
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)

    implementation(libs.sage.common.logging)
    implementation(libs.kotlinx.coroutines.core)
}
