plugins {
    alias(libs.plugins.sage.jvm)
    alias(libs.plugins.ksp)
    // Compose Multiplatform desktop. Two plugins are needed: the Kotlin Compose compiler
    // (shared with the Android UI) handles @Composable codegen, and the JetBrains Compose
    // plugin provides the `compose.desktop.currentOs` dependency notation that resolves the
    // per-OS Skia native artifact. Both must be applied here; only the compiler plugin will
    // travel through the future sage.compose.kmp convention for shared UI modules.
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.compose.multiplatform)
    application
}

application {
    mainClass.set("net.sigmabeta.chipbox.jvm.MainKt")
}

// libgme.so is host-built (see apps/jvm/README) into apps/jvm/libs and loaded at runtime via
// System.loadLibrary("gme"); point the JVM library path at it for `gradle run`.
val nativeLibsDir = layout.projectDirectory.dir("libs")

tasks.named<JavaExec>("run") {
    systemProperty("java.library.path", nativeLibsDir.asFile.absolutePath)
}

// Emit a ready-to-run `java` invocation (no Gradle at runtime). Many modules share a jar
// basename (real.jar/api.jar), which breaks the flat-lib `installDist`; an explicit
// classpath of full, unique jar paths sidesteps that. Writes build/run-standalone.sh.
tasks.register("standaloneScript") {
    val rtFiles: FileCollection = configurations.getByName("runtimeClasspath")
    val jarFile = tasks.named<Jar>("jar").flatMap { it.archiveFile }
    val mainClass = application.mainClass
    val libDir = nativeLibsDir.asFile.absolutePath
    val outFile = layout.buildDirectory.file("run-standalone.sh")
    inputs.files(rtFiles, jarFile)
    outputs.file(outFile)
    doLast {
        val cp = (listOf(jarFile.get().asFile) + rtFiles.files)
            .joinToString(":") { it.absolutePath }
        val f = outFile.get().asFile
        f.writeText(
            "#!/usr/bin/env bash\n" +
                "# Generated by :apps:jvm:standaloneScript — runs without Gradle.\n" +
                "exec java -Djava.library.path='$libDir' \\\n" +
                "  -cp '$cp' \\\n" +
                "  ${mainClass.get()} \"\$@\"\n"
        )
        f.setExecutable(true)
        logger.lifecycle("Wrote ${f.absolutePath}")
    }
}

dependencies {
    implementation(projects.cbox.android.player.generator.real)
    implementation(projects.cbox.android.player.emulators.gba.real)
    implementation(projects.cbox.android.player.emulators.gme.real)
    implementation(projects.cbox.android.player.emulators.psf.real)
    implementation(projects.cbox.android.player.emulators.ssf.real)
    implementation(projects.cbox.android.player.emulators.twosf.real)
    implementation(projects.cbox.android.player.emulators.usf.real)
    implementation(projects.cbox.android.player.emulators.vgm.real)
    implementation(projects.cbox.common.contentsource.api)
    implementation(projects.cbox.common.strings.api)
    implementation(projects.cbox.common.debug.api)
    implementation(projects.cbox.common.debug.real)
    implementation(projects.cbox.common.settings.api)
    implementation(projects.cbox.common.settings.real)
    implementation(projects.cbox.common.player.speaker.fake)
    implementation(projects.cbox.common.player.buffer.real)
    implementation(projects.cbox.common.player.common.api)
    implementation(projects.cbox.common.repository.api)
    implementation(projects.cbox.common.models.api)

    // Room KMP database used as the JVM target's real library (replaces the
    // SingleTrackRepository shim for `scan` / `play` modes). `sqlite-bundled`
    // is the cross-platform Room driver Android doesn't need.
    implementation(projects.cbox.android.repository.real)
    implementation(projects.cbox.android.database.all)
    implementation(libs.sqlite.bundled)

    // Shared scanner — uses the new LibrarySource interface; LocalFileContentSource
    // is the JVM impl, the Android twin is AndroidFileContentSource (SAF).
    implementation(projects.cbox.android.scanner.real)
    implementation(projects.cbox.common.readers.api)

    // Plain Dagger — the headless JVM target assembles its own @Component. Hilt is
    // Android-only by design, so the JVM-side `@Module` classes (see jvm/di/) duplicate
    // the trivial @Provides for each emulator + buffer + repository binding; that's
    // simpler than wiring sage.android Hilt modules into a sage.jvm app's classpath.
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)

    implementation(libs.sage.common.logging)
    implementation(libs.sage.common.appinfo)
    implementation(libs.sage.common.storage.common)
    implementation(libs.kotlinx.coroutines.core)

    // Compose Multiplatform desktop. The platform-agnostic libs come from the catalog so
    // shared UI modules (future sage.compose.kmp) pin the exact same versions; the per-OS
    // Skia native is pulled via `compose.desktop.currentOs` from the JetBrains plugin
    // extension applied above. Bootstrap inlines its Hello composable in DesktopMain.kt;
    // these deps will mostly move into shared modules in follow-up slices.
    implementation(libs.jetbrains.compose.runtime)
    implementation(libs.jetbrains.compose.foundation)
    implementation(libs.jetbrains.compose.material3)
    implementation(libs.jetbrains.compose.ui)
    implementation(compose.desktop.currentOs)

    // Shared Chipbox color schemes + typography + ChipboxTheme — same palette / type structure
    // the Android UI uses via cbox/android/ui/theme/api. Transitively pulls
    // cbox/common/ui/fonts/api (via api()), so the JVM target gets real Chipbox pixel-art
    // fonts via Compose Multiplatform resources.
    implementation(projects.cbox.common.ui.theme.api)

    // Multiplatform ChipboxViewModel + LocalViewModelProvider — consumed by the demo
    // HelloViewModel and the JvmViewModelProvider that wires it into DesktopMain.
    implementation(projects.cbox.common.ui.vm.api)

    // Voyager — Compose Multiplatform navigation. Replaces what would otherwise be
    // androidx.navigation:navigation-compose (the AndroidX CMP fork publishes JVM stubs
    // only, no runtime). Each screen implements `Screen`; `Navigator(MyScreen())` owns
    // the back stack.
    implementation(libs.voyager.navigator)
}
